name: Build Docker Images

on:
  workflow_call:
    inputs:
      extra_args:
        description: Extra args for go-releaser, for example '--snapshot'
        required: false
        type: string
      version:
        description: Version of base image
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: centralmind/gateway
      VERSION: ${{ github.event.release.tag_name || github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx build --platform linux/amd64 \
            --build-arg TARGETARCH=amd64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --file Dockerfile.build \
            --push \
            .

      - name: Tag Release Images
        if: github.event_name == 'release'
        run: |
          docker buildx build --platform linux/amd64 \
            --build-arg TARGETARCH=amd64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }} \
            --file Dockerfile.build \
            --push \
            .
